spring.application.name=starter-demo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cloudServiceProject?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

homelab.ip=http://192.168.50.204:30401/
